### ISSUE TITLE
Confusing description of try method

### ISSUE THREAD

**Issue by ahlevering** [GeoScripting-WUR/RProjectManagement#14]
Hello guys,

As requested by Jan, hereby I'd like to convey some student feedback on the way that the try method is explained. It pertains the following piece of code:
```
fun <- function(x, value) {
    tr <- try(freq(x=x, value=value), silent=TRUE)
    if (class(tr) == 'try-error') {
        return('This object returned an error')
    } else {
        return(tr)
    }
}
```

The example here explains the Try function by using the freq method, which in itself is clear if you understand what both are supposed to do. However, this part was was not immediately clear for some students as it was interpreted that freq was a necessary part of the try clause. Would it perhaps be a better idea to explain the try method by using a boolean with an added comment that it can evaluate any variable or method?

Yours truly,
Alex

**Comment by GreatEmerald** [comment]
I added a copy of the previous code block (where `freq` is used outside of a function), simply wrapping the same `freq()` call in a `try()`, before the more complicated example with functions, in pull #15. That ought to be clear enough now.
