### ISSUE TITLE
clarify even better that students should work via the linux available workspace

### ISSUE THREAD

**Issue by janverbesselt** [GeoScripting-WUR/RProjectManagement#18]
This sentence  
" Important note: you need to have git installed and properly configured on your computer to do the following. Visit the system setup page for more details. Git is preinstalled in the PC lab and on virtual machines already."

Is not clear enough. We need to say at the start that Git is available via VMWare - WorkSpace etc. - and so the work from within Linux OS with Git.

We can also add that as a key point in Black Board or the replacement of it in 2020.

**Comment by GreatEmerald** [comment]
Done - added a large blue box at the top linking to the VMWare Horizon setup. But we should *also* write that on Brightspace.
