### ISSUE TITLE
adding a simple exercise  (2020 geoscripting)

### ISSUE THREAD

**Issue by janverbesselt** [GeoScripting-WUR/RProjectManagement#21]
Goal of the exercise:

- set up a correct project structure
- with a simple age calculator function

To do:

- make it automatically gradable via CodeGrade or  GithubClassroom

Learning outcomes:

- learning about a what a good project structure is and how a simple function works and can be used.
- learning relative paths

**Comment by GreatEmerald** [comment]
Done: https://github.com/geoscripting-innovation/Exercise1-solution
